name: User Story
description: Création d'une User Story standardisée
title: "[US] "
labels:
  - user story
assignees: []

body:
  - type: dropdown
    id: ref
    attributes:
      label: Ref
      description: Numéro de la User Story
      options:
        - US01
        - US02
        - US03
        - US04
        - US05
        - US06
        - US07
        - US08
        - US09
        - US10
    validations:
      required: true

  - type: dropdown
    id: role
    attributes:
      label: En tant que
      description: Rôle de l'utilisateur
      options:
        - secrétaire
        - coach
        - parent
        - joueur
    validations:
      required: true

  - type: textarea
    id: want
    attributes:
      label: Je veux…
      description: Action ou besoin exprimé
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Afin de…
      description: Objectif métier
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      description: Niveau de priorité
      options:
        - 1
        - 2
        - 3
    validations:
      required: true

  - type: dropdown
    id: us_point
    attributes:
      label: US Point
      description: Charge estimée (complexité)
      options:
        - 1
        - 2
        - 3
        - 5
        - 8
    validations:
      required: true
